substitutions:
  name: "dishwasher"
  friendly_name: "Dishwasher"
  relay_restore_mode: RESTORE_DEFAULT_ON
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 10.0.0.111
    gateway: 10.0.0.1
    subnet: 255.255.255.0
  
text_sensor:
  - platform: template
    name: "Dishwasher Current State"
    id: dishwasher_current_state


binary_sensor:

#Dishwasher Running Check
#if the machine uses more than 4W it is deemed to be running
#after an entire cycle (deemed no longer running) it will update all binary sensors to false (i would like to move to only the one text sensor and maybe a single running yes/no sensor)

  - platform: template
    name: "Dishwasher Running"
    id: dishwasher_running
    filters:
      - delayed_on: 30s
      - delayed_off: 320s
    lambda: |-
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if (id(power_sensor).state > 4) {
        return true;
      } else {
        return false;
      }
    on_press:
      then:
      - lambda: |-  
            {
              id(dishwasher_current_state).publish_state("Running");
            }
    on_release:
      then:
        - lambda: |-  
            {
              id(dishwasher_end).publish_state(true);
              id(dishwasher_first_rinse).publish_state(false);
              id(dishwasher_minimum_working_time).publish_state(false);
              id(dishwasher_heated_wash).publish_state(false);
              id(dishwasher_passive_wash).publish_state(false);
              id(dishwasher_heated_rinse).publish_state(false);
              id(dishwasher_drying).publish_state(false);
              id(dishwasher_current_state).publish_state("Ended");
            }

#Minimum Cycle time
#machine needs to be running for at least 1 minute to count as on and move onto the first stage
#this could potentially be shortened in the future

  - platform: template
    name: "Minimum time"
    internal: true
    id: dishwasher_minimum_working_time 
    filters:
      - delayed_on: 60s
      - delayed_off: 300s
    lambda: |-
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if (id(power_sensor).state > 4) {
        // Running
        return true;
      } else {
        // Not running
        return {};
      }

#First Rinse
#this cycle just appears to turn on the pump, so power draw does not exceed ~70W for a majority of the cycle
#there is a brief peak, which is why the sensor is between 10 and 300
#i chose not to delay the off, because i wanted transitions to be as consistent as possible

  - platform: template
    name: "Dishwasher First Rinse"
    id: dishwasher_first_rinse
    filters:
      - delayed_on: 60s
    lambda: |-  
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if ( (id(power_sensor).state > 10)&&(id(power_sensor).state < 300)&&(id(dishwasher_minimum_working_time).state) ){
        // Running
        return true;
      } else {
        // Not running
        return {};
      }
    on_press:
      then:
      - lambda: |-  
            {
              id(dishwasher_current_state).publish_state("First Rinse");
            }

#Heated Wash
#for this stage the dishwasher heats up water resulting in a larger power draw

  - platform: template
    name: "Dishwasher Heated Wash"
    id: dishwasher_heated_wash
    filters:
      - delayed_on: 60s 
    lambda: |-  
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if ( (id(power_sensor).state > 250) && (id(power_sensor).state < 2500) && (id(dishwasher_first_rinse).state) ){
        // Running
        return true;
      } else {
        // Not running
        return {};
      }           
    on_press:
      then:
      - lambda: |-  
            {
              id(dishwasher_current_state).publish_state("Heated Wash");
            }

#Passive Wash
#this cycle continues to feed off the already heated water from previous cycle and continues the wash

  - platform: template
    name: "Dishwasher Passive Wash"
    id: dishwasher_passive_wash
    filters:
      - delayed_on: 60s 
    lambda: |-  
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if ( (id(power_sensor).state > 10) && (id(power_sensor).state < 100) && (id(dishwasher_heated_wash).state) ){
        // Running
        return true;
      } else {
        // Not running
        return {};
      }   
    on_press:
      then:
      - lambda: |-  
            {
              id(dishwasher_current_state).publish_state("Passive Wash");
            }

#Heated Rinse
#machine heats up water again
#the manual says this is not a full wash so it is likely that the machine in removing any streaks/leftover suds from detergent
#this cycle has a delayed off as there is a brief dip at the start which falls within perameters for the next stage

  - platform: template
    name: "Dishwasher Heated Rinse"
    id: dishwasher_heated_rinse
    filters:
      - delayed_on: 60s 
      - delayed_off: 90s 
    lambda: |-  
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if ( (id(power_sensor).state > 300) && (id(power_sensor).state < 2500) && (id(dishwasher_passive_wash).state) ){
        // Running
        return true;
      } else {
        // Not running
        return {};
      }
    on_press:
      then:
      - lambda: |-  
            {
              id(dishwasher_current_state).publish_state("Heated Rinse");
            }

#Drying
#this stage is internally a mystery. potentially also a passive rinse phase
#we used to think this stage used the same power as a heating phase, but it seems to use the least
#i may come back to this one in the future and split it into 2

  - platform: template
    name: "Dishwasher Drying"
    id: dishwasher_drying
    filters:
      - delayed_on: 60s 
    lambda: |-  
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if ( (id(power_sensor).state > 10) && (id(power_sensor).state < 80) && (id(dishwasher_heated_rinse).state) ){
        // Running
        return true;
      } else {
        // Not running
        return {};
      }
    on_press:
      then:
      - lambda: |-  
            {
              id(dishwasher_current_state).publish_state("Drying");
            }

#Ended
#this sensor exists purely to be updated by other sensors

  - platform: template
    name: "Dishwasher Ended"
    id: dishwasher_end