substitutions:
  name: "dishwasher"
  friendly_name: "Dishwasher"
  relay_restore_mode: RESTORE_DEFAULT_ON
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
binary_sensor:

################################################################################
#                               Machine running                                #
################################################################################
  - platform: template
    name: "RUN"
    id: machine_running
    filters:
      - delayed_on: 60s # MINIMUM TIME TO AVOID FALSE POSITIVES
      - delayed_off: 300s
    lambda: |-
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if (id(power_sensor).state > 4) {
        // Running
        return true;
      } else {
        // Not running
        return false;
      }
    on_press:
      then: # at cycle start i reset all binary sensors
        #Moved to end, because states all reset when the machine finishes, surely?
        #- lambda: |-  
        #    {
        #      id(first_rinse).publish_state(false);
        #      id(minimum_working_time).publish_state(false);
        #      id(heated_wash).publish_state(false);
        #      id(passive_wash).publish_state(false);
        #      id(heated_rinse).publish_state(false);
        #      id(drying).publish_state(false);
        #    }
    on_release:
      then: # at the end of cycle turn on end cycle
        - lambda: |-  
            {
              id(machine_end).publish_state(true);
              id(first_rinse).publish_state(false);
              id(minimum_working_time).publish_state(false);
              id(heated_wash).publish_state(false);
              id(passive_wash).publish_state(false);
              id(heated_rinse).publish_state(false);
              id(drying).publish_state(false);
            }        
################################################################################
#                           Minimum duration cycle                             #
################################################################################
  - platform: template
    name: "Washing Machine Minimum time"
    internal: true # minimum working time 30m
    id: minimum_working_time 
    filters:
      - delayed_on: 5min
      - delayed_off: 180s
    lambda: |-
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if (id(power_sensor).state > 4) {
        // Running
        return true;
      } else {
        // Not running
        return {};
      }
################################################################################
#                             FIRST RINSE                                      #
################################################################################
  - platform: template
    name: "FIRST RINSE"
    id: first_rinse
    filters:
      - delayed_on: 60s
    lambda: |-  
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if ( (id(power_sensor).state > 10)&&(id(power_sensor).state < 300)&&(id(minimum_working_time).state) ){
        // Running
        return true;
      } else {
        // Not running
        return {};
      }
################################################################################
#                             HEATED RINSE                                     #
################################################################################
  - platform: template
    name: "HEATED RINSE"
    id: heated_wash
    filters:
      - delayed_on: 60s 
    lambda: |-  
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if ( (id(power_sensor).state > 250) && (id(power_sensor).state < 2500) && (id(first_rinse).state) ){
        // Running
        return true;
      } else {
        // Not running
        return {};
      }           
################################################################################
#                            PASSIVE WASH                                      #
################################################################################
  - platform: template
    name: "PASSIVE WASH"
    id: passive_wash
    filters:
      - delayed_on: 60s 
    lambda: |-  
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if ( (id(power_sensor).state > 15) && (id(power_sensor).state < 300) && (id(heated_wash).state) ){
        // Running
        return true;
      } else {
        // Not running
        return {};
      }   
################################################################################
#                           HEATED RINSE                                       #
################################################################################
  - platform: template
    name: "HEATED RINSE"
    id: heated_rinse
    filters:
      - delayed_on: 300s 
    lambda: |-  
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if ( (id(power_sensor).state > 300) && (id(power_sensor).state < 2500) && (id(passive_wash).state) ){
        // Running
        return true;
      } else {
        // Not running
        return {};
      }
################################################################################
#                                DRYING                                        #
################################################################################
  - platform: template
    name: "DRYING"
    id: drying
    filters:
      - delayed_on: 60s 
    lambda: |-  
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if ( (id(power_sensor).state > 10) && (id(power_sensor).state < 80) && (id(heated_rinse).state) ){
        // Running
        return true;
      } else {
        // Not running
        return {};
      }
################################################################################
#                                 Machine end                                  #
################################################################################
  - platform: template
    name: "END"
    id: machine_end
################################################################################